#!/bin/sh

while read name ; do 
read l1
read l2 num rest
name=$(echo "$name"|tr -d \\015 |sed 's/ *$//')
name=$(echo "$name"|sed 's/IRIDIUM/ /')
echo "$num \"$name\" image=satellites/sat.png transparent={0,0,0} color={70,70,250} fontsize=9 trail={orbit,-5,0,1}"
done

exit 0
